# <font color='white'> 4. Study Case 4: Youtube Videos
- Diberikan dua buah data :
    - `youtube-videos-1.csv`
    - `youtube-videos-2.csv`
- Data tersebut merupakan data pada tahun 2023.

In [1]:
import pandas as pd

rawYoutubeDF_1 = pd.read_csv("youtube-videos-1.csv")
rawYoutubeDF_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          200 non-null    object
 1   published_at   200 non-null    object
 2   duration       200 non-null    object
 3   view_count     200 non-null    int64
 4   like_count     197 non-null    float64
 5   comment_count  193 non-null    float64
dtypes: float64(2), int64(1), object(3)
memory usage: 9.5+ KB

In [2]:
# Preview data
rawYoutubeDF_1.head()

,title,published_at,duration,view_count,like_count,comment_count
0,Let's see if you dare next time #Shorts #017,2023-04-25T02:40:11Z,PT18S,246200629,1572774.0,942.0
1,[6Î≤à] ÏãùÎãπ ÏóÖÏÜåÏö© ÏùåÏãùÌè¨Ïû• ÎπÑÎãêÎû© Ï†àÎã®Í∏∞,2023-05-11T07:08:02Z,PT15S,160984366,1472323.0,678.0
2,Khaby Lame react epic moments #shorts #kabhylame,2023-05-12T09:35:22Z,PT19S,96455747,2312319.0,2203.0
3,Polina Knoroz's Cute Moment in Sports #shorts,2023-06-11T13:30:04Z,PT35S,91902366,1397067.0,930.0
4,Salute to indian armyüáÆüá≥‚ù§Ô∏èüíØ #army #trending #vi...,2023-05-05T14:00:16Z,PT30S,85157682,1973374.0,0.0

In [3]:
rawYoutubeDF_2 = pd.read_csv("youtube-videos-2.csv")
rawYoutubeDF_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          280 non-null    object
 1   published_at   280 non-null    object
 2   duration       280 non-null    object
 3   view_count     280 non-null    int64
 4   like_count     280 non-null    float64
 5   comment_count  276 non-null    float64
dtypes: float64(2), int64(1), object(3)
memory usage: 13.3+ KB

In [4]:
# Preview data
rawYoutubeDF_2.head()

,title,published_at,duration,view_count,like_count,comment_count
0,Imlie | ‡§á‡§Æ‡§≤‡•Ä | Imlie aur Aryan ki shaadi ke sp...,2023-04-08T12:00:42Z,PT9M17S,731419,7741.0,127.0
1,Taylor Swift feels a bit anxious while signing...,2023-12-11T02:02:13Z,PT33S,743408,79234.0,134.0
2,Imlie | ‡§á‡§Æ‡§≤‡•Ä |Nimbu paani samjhkar Imlie ne pi...,2023-03-14T14:31:34Z,PT10M5S,728467,6439.0,39.0
3,Imlie | ‡§á‡§Æ‡§≤‡•Ä | Kyun nahi lagayi Imlie ne Aryan...,2023-04-07T16:00:23Z,PT11M56S,719893,7261.0,71.0
4,25 Most Beautiful Caribbean Islands | Best Car...,2023-04-29T16:33:27Z,PT47M3S,720998,5245.0,206.0

- **Gabungkan kedua data tersebut.**
- Gabung dengan menggunakan method `.concat()`
- Penggabungan yang dilakukan adalah **penggabungan baris.**
- Ketentuan :
    - **Top table:**
        - `yt_videos_1`
    - **Bottom table:**
        - `yt_videos_2`
- Notes :
    - Buat indexnya menjadi continue.

In [5]:
# Join the dataframes
youtubeDF = pd.concat(
    [
        rawYoutubeDF_1,
        rawYoutubeDF_2
    ],
    axis=0,
    ignore_index=True
)

# Preview the data
youtubeDF.head()

,title,published_at,duration,view_count,like_count,comment_count
0,Let's see if you dare next time #Shorts #017,2023-04-25T02:40:11Z,PT18S,246200629,1572774.0,942.0
1,[6Î≤à] ÏãùÎãπ ÏóÖÏÜåÏö© ÏùåÏãùÌè¨Ïû• ÎπÑÎãêÎû© Ï†àÎã®Í∏∞,2023-05-11T07:08:02Z,PT15S,160984366,1472323.0,678.0
2,Khaby Lame react epic moments #shorts #kabhylame,2023-05-12T09:35:22Z,PT19S,96455747,2312319.0,2203.0
3,Polina Knoroz's Cute Moment in Sports #shorts,2023-06-11T13:30:04Z,PT35S,91902366,1397067.0,930.0
4,Salute to indian armyüáÆüá≥‚ù§Ô∏èüíØ #army #trending #vi...,2023-05-05T14:00:16Z,PT30S,85157682,1973374.0,0.0

- Sebelum melakukan pengelompokkan, lakukan :
    - **Casting** tipe data dari kolom `published_at` menjadi datetime.
    - Ekstrak kolom `published_at`
    - **Buat kolom baru** untuk menyimpan data hasil ekstraksi

In [6]:
# Format "published_at" column as datetime
youtubeDF["published_at"] = pd.to_datetime(youtubeDF["published_at"])
# Extract "published_at" column
## Extract year
youtubeDF["year_published"] = youtubeDF["published_at"].dt.year
## Extract month
youtubeDF["month_published"] = youtubeDF["published_at"].dt.month
## Extract date
youtubeDF["day_published"] = youtubeDF["published_at"].dt.date
## Delete published_at
youtubeDF = youtubeDF.drop(columns="published_at")
# Preview the dataframe
youtubeDF.head()

,title,duration,view_count,like_count,comment_count,year_published,month_published,day_published
0,Let's see if you dare next time #Shorts #017,PT18S,246200629,1572774.0,942.0,2023,4,2023-04-25
1,[6Î≤à] ÏãùÎãπ ÏóÖÏÜåÏö© ÏùåÏãùÌè¨Ïû• ÎπÑÎãêÎû© Ï†àÎã®Í∏∞,PT15S,160984366,1472323.0,678.0,2023,5,2023-05-11
2,Khaby Lame react epic moments #shorts #kabhylame,PT19S,96455747,2312319.0,2203.0,2023,5,2023-05-12
3,Polina Knoroz's Cute Moment in Sports #shorts,PT35S,91902366,1397067.0,930.0,2023,6,2023-06-11
4,Salute to indian armyüáÆüá≥‚ù§Ô∏èüíØ #army #trending #vi...,PT30S,85157682,1973374.0,0.0,2023,5,2023-05-05

- **Lakukan pengelompokkan data** berdasarkan kolom `month_published`

In [8]:
# Group the dataframe based on "month_published"
youtubeDFGrouped = youtubeDF.groupby("month_published", sort=True)

- Menampilkan **urutan data dengan jumlah view terbanyak pada tahun 2023.** berdasarkan pengelompokan tersebut

In [9]:
# Get indexes of records with highest view_count in each group
highestViewCountIndexes = (
    youtubeDFGrouped
    ["view_count"]
    .idxmax()
)
# Get all records that match the filter
filteredYoutubeDF = youtubeDF.loc[highestViewCountIndexes]
filteredYoutubeDF

,title,duration,view_count,like_count,comment_count,year_published,month_published,day_published
12,Amazing Masala Guava | traditional food home,PT44S,45966884,1814779.0,2909.0,2023,1,2023-01-06
6,Khaby Lame react epic moments #shorts #kabhylame,PT24S,68627526,1720630.0,907.0,2023,2,2023-02-16
7,Happiness ‚ù§Ô∏è | Wild Cookbook,PT58S,61273357,2385050.0,6365.0,2023,3,2023-03-18
0,Let's see if you dare next time #Shorts #017,PT18S,246200629,1572774.0,942.0,2023,4,2023-04-25
1,[6Î≤à] ÏãùÎãπ ÏóÖÏÜåÏö© ÏùåÏãùÌè¨Ïû• ÎπÑÎãêÎû© Ï†àÎã®Í∏∞,PT15S,160984366,1472323.0,678.0,2023,5,2023-05-11
3,Polina Knoroz's Cute Moment in Sports #shorts,PT35S,91902366,1397067.0,930.0,2023,6,2023-06-11
115,DD News 24x7 | Breaking News & Latest Updates ...,P0D,2073512,6667.0,NaN,2023,9,2023-09-26
293,LIVE üî¥ C√¢ntece TraLaLa pentru Copii de GrƒÉdini...,P0D,367614,2037.0,0.0,2023,11,2023-11-27
91,Tose Nainaa Milaai Ke | 10 December 2023 | Ful...,PT22M9S,3114372,42448.0,732.0,2023,12,2023-12-10

- Menampikan **urutan data dengan jumlah view terbanyak pada bulan februari tahun 2023.**

In [11]:
# Group the dataframe based on "year_album"
febYoutubeDF = (
    youtubeDFGrouped.get_group(2)
)
# Sort the dataframe
sortedFebYoutubeDF = (
    febYoutubeDF
    .sort_values(
        by="view_count", 
        ascending=False,
        ignore_index=True
    )
)
sortedFebYoutubeDF

,title,duration,view_count,like_count,comment_count,year_published,month_published,day_published
0,Khaby Lame react epic moments #shorts #kabhylame,PT24S,68627526,1720630.0,907.0,2023,2,2023-02-16
1,DILU Beats - Numba Ha (Suraganak Wilasa) - Off...,PT2M44S,17973032,114304.0,6422.0,2023,2,2023-02-05
2,toy car towed by crane #shorts,PT40S,15084784,837257.0,1105.0,2023,2,2023-02-17
3,‡∂ö‡∑ú‡∂∏‡∑Ö‡∑í | Komali - Jaanu Teledrama Theme Song | ITN,PT3M11S,8358892,54222.0,1317.0,2023,2,2023-02-17
4,Baby Jackfruit (Polos) Patties | Wild Cookbook,PT1M,6236748,311156.0,642.0,2023,2,2023-02-21
5,How to draw rose flower very easy #shorts,PT31S,5863446,204722.0,565.0,2023,2,2023-02-11
6,Fsboling-Professional woodworking machinery,PT10S,5053466,18133.0,133.0,2023,2,2023-02-08
7,Weight Loss Workout easily at home #weightloss...,PT5S,4151404,99143.0,63.0,2023,2,2023-02-25
8,Red lady Papayas! Yellow ones for sweets & des...,PT23M3S,3928994,27755.0,906.0,2023,2,2023-02-17
9,Catriona gray üëë Miss universe 2018 üòç Swimsuit ...,PT32S,2683122,93435.0,495.0,2023,2,2023-02-19
10,Doctor Reacts To Anatomy Lessons & First Ever ...,PT48S,2028783,134909.0,1050.0,2023,2,2023-02-28
11,Floury pumpkinsüéÉ!!Entire family enjoy every to...,PT20M17S,1838574,29928.0,2096.0,2023,2,2023-02-09
12,@LakaiSikai - Lakaa Ko ü§®üò≥‚ÅâÔ∏è| ‡∂Ω‡∂ö‡∂∫‡∑í ‡∑É‡∑í‡∂ö‡∂∫‡∑í - ‡∂Ω‡∂ö‡∑è...,PT28M18S,1643421,47384.0,1381.0,2023,2,2023-02-01
13,Poornima Lakshani | Mal Mal Sariya (‡∂∏‡∂Ω‡∑ä ‡∂∏‡∂Ω‡∑ä ‡∑É‡∑è...,PT12M32S,1003127,23056.0,931.0,2023,2,2023-02-12
14,Car buying made easy | Clutch :15s,PT16S,882303,14.0,0.0,2023,2,2023-02-21
15,40 Important ROAD SIGNS That You Need To Know ...,PT5M20S,833431,7572.0,150.0,2023,2,2023-02-28
16,Explosion-Proof Zombies??? #shorts #pvzmods #pvz,PT29S,780924,23721.0,39.0,2023,2,2023-02-28
17,Large Monster crabü¶Ämeat is tender with coconut...,PT20M10S,773008,7612.0,77.0,2023,2,2023-02-10
18,Amazing Create Woodworking Drill Stands #woodw...,PT1M,737847,12462.0,45.0,2023,2,2023-02-20
19,Tere dil ka mere dil se song Reverb - Ye Hai M...,PT5M48S,374681,1813.0,24.0,2023,2,2023-02-02
20,Batman and Wonder Woman Love Story,PT6M5S,332343,5048.0,191.0,2023,2,2023-02-16
21,Eliminate FPS Stutters with this ONE SETTING o...,PT5M6S,299902,7224.0,444.0,2023,2,2023-02-09
22,–¢–æ—Ä—Ç ¬´–¢–†–ò –°–¢–ê–ö–ê–ù–ê¬ª #—Ç–æ—Ä—Ç #—Ä–µ—Ü–µ–ø—Ç—ã #shorts,PT44S,271121,14398.0,84.0,2023,2,2023-02-16
23,ChatGPT Makes PowerPoint Slides For You ü§© || @...,PT59S,226208,5371.0,36.0,2023,2,2023-02-27
24,"""Eagle 44""-‡Æê ‡Æµ‡Øà‡Æ§‡Øç‡Æ§‡ØÅ Israel-‡Æê ‡ÆÆ‡Æø‡Æ∞‡Æü‡Øç‡Æü‡ØÅ‡ÆÆ‡Øç Iran |...",PT10M23S,225088,2650.0,105.0,2023,2,2023-02-11

In [3]:
a = set([1,2,4,5,6,3,3,13,31,3])
b = set([1,2,4,5,3,6,3,13,31,3])
b

{1, 2, 3, 4, 5, 6, 13, 31}